name: goorm_3355
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '^3.0.0'


dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  carousel_slider: ^4.2.1
  cupertino_icons: ^1.0.5
  flutter_svg: ^0.22.0  # null safety를 지원하는 버전으로 업데이트
  firebase_core: "2.13.0"
  firebase_auth: ^4.6.1
  cloud_firestore: "4.7.1"
  firebase_storage: "11.2.1"
  kakao_flutter_sdk: ^1.4.3
  marquee: ^2.1.0
  shared_preferences: ^2.1.1
  rxdart: ^0.27.7
  cached_network_image: ^3.2.3
  flutter_rating_bar: ^4.0.1
  url_launcher: ^6.1.11
  flutter_form_builder: ^9.0.0
  intl: ^0.18.1


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
